# Site settings
title: The LaTeX Project
# email: your-email@domain.com
# description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://latex3.github.io/latex-project.org"
url: "https://latex-project.org/"
#twitter_username: 
#github_username:  

# Build settings
markdown: kramdown
# enable recognition of Github Flavored Markdown (GFM)
# kramdown:
#  input: GFM

# Permalinks
# http://jekyllrb.com/docs/permalinks/
# permalink: date|pretty|ordinal|none
permalink: pretty
