name: Deploy
on:
  push:
    branches:
      - main
      - live
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@52753b7da854d5c07df37391a986c76ab4615999
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Jekyll Build
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
  deploy-gh:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Deploy to Pages
        id: deployment
        uses: zauguin/custom-pages@trunk
        with:
          server: https://deploy.latex-project.org
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  deploy-live:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/live'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Deploy to Pages
        id: deployment
        uses: zauguin/custom-pages@trunk
        with:
          server: https://deploy.latex-project.org
    environment:
      name: deploy-live
      url: ${{ steps.deployment.outputs.page_url }}
