name: Deploy
on:
  push:
    branches:
      - live
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy-live
    steps:
      - uses: actions/checkout@v4
      - name: Setup SSH
        env:
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE" > ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_CONFIG" > ~/.ssh/config
      - name: Copy content
        run: |
          rsync -rlpz --delete _site/ deploy:
